app:
  build:
    context: ""
    dockerfile: ./docker/Dockerfile
  restart: always
  working_dir: /var/www/
  volumes:
    - ./src:/var/www

  # nginx
  nginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d